# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build jacocoTestReport

    - name: Upload Jacoco Coverage Report
      uses: actions/upload-artifact@v4.3.3
      with:
        name: jacoco-report-${{ matrix.os }}
        path: headless/build/reports/jacoco/test/html/

    - name: Upload JAR file
      uses: actions/upload-artifact@v4.3.3
      with:
        name: UniSim-latest-${{ matrix.os }}.jar
        path: lwjgl3/build/libs/UniSim-latest.jar

  dependency-submission:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

  release:
    runs-on: ubuntu-latest
    needs: [ "build" ]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
    # Ubuntu
    - name: Download Ubuntu Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: UniSim-latest-ubuntu-latest.jar
    - name: Rename Ubuntu Build Artifact
      run: mv UniSim-latest.jar UniSim-latest-ubuntu.jar

    # Windows
    - name: Download Windows Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: UniSim-latest-windows-latest.jar
    - name: Rename Windows Build Artifact
      run: mv UniSim-latest.jar UniSim-latest-windows.jar

    # MacOS
    - name: Download MacOS Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: UniSim-latest-macos-latest.jar
    - name: Rename MacOS Build Artifact
      run: mv UniSim-latest.jar UniSim-latest-macos.jar

    # Debug step - recursively lists all files
    - name: List Files
      run: ls -R

    # The actual release
    - name: Release
      uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
      with:
        files: UniSim-*.jar

